// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCotJNMNmuX5Pr2FsjSYyoDfxDzL7c9fBs',
    appId: '1:154493590022:web:bb2fe000bb1b65ffbb0187',
    messagingSenderId: '154493590022',
    projectId: 'tarutaru-walk',
    authDomain: 'tarutaru-walk.firebaseapp.com',
    databaseURL: 'https://tarutaru-walk-default-rtdb.firebaseio.com',
    storageBucket: 'tarutaru-walk.appspot.com',
    measurementId: 'G-WQZL65KJ8X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0QlkXU4DalFoi71pNh_roepuSUCiNYA4',
    appId: '1:154493590022:android:94e5f59d50661cffbb0187',
    messagingSenderId: '154493590022',
    projectId: 'tarutaru-walk',
    databaseURL: 'https://tarutaru-walk-default-rtdb.firebaseio.com',
    storageBucket: 'tarutaru-walk.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJECM1SZTLgGveRoSHzHRJnCfAGue4mLI',
    appId: '1:154493590022:ios:0ea8a10df77f0b07bb0187',
    messagingSenderId: '154493590022',
    projectId: 'tarutaru-walk',
    databaseURL: 'https://tarutaru-walk-default-rtdb.firebaseio.com',
    storageBucket: 'tarutaru-walk.appspot.com',
    iosBundleId: 'com.example.beaconApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJECM1SZTLgGveRoSHzHRJnCfAGue4mLI',
    appId: '1:154493590022:ios:bd07e63d7c87ae15bb0187',
    messagingSenderId: '154493590022',
    projectId: 'tarutaru-walk',
    databaseURL: 'https://tarutaru-walk-default-rtdb.firebaseio.com',
    storageBucket: 'tarutaru-walk.appspot.com',
    iosBundleId: 'com.example.beaconApp.RunnerTests',
  );
}
